// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package modals

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5170dbe5DecodeLibraryPycEduHkAttendancePkgModals(in *jlexer.Lexer, out *Records) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "records":
			if in.IsNull() {
				in.Skip()
				out.Records = nil
			} else {
				in.Delim('[')
				if out.Records == nil {
					if !in.IsDelim(']') {
						out.Records = make([]*Attendance, 0, 8)
					} else {
						out.Records = []*Attendance{}
					}
				} else {
					out.Records = (out.Records)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Attendance
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Attendance)
						}
						if data := in.Raw(); in.Ok() {
							in.AddError((*v1).UnmarshalJSON(data))
						}
					}
					out.Records = append(out.Records, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5170dbe5EncodeLibraryPycEduHkAttendancePkgModals(out *jwriter.Writer, in Records) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Records) != 0 {
		const prefix string = ",\"records\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v2, v3 := range in.Records {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					out.Raw((*v3).MarshalJSON())
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Records) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5170dbe5EncodeLibraryPycEduHkAttendancePkgModals(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Records) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5170dbe5EncodeLibraryPycEduHkAttendancePkgModals(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Records) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5170dbe5DecodeLibraryPycEduHkAttendancePkgModals(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Records) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5170dbe5DecodeLibraryPycEduHkAttendancePkgModals(l, v)
}
func easyjson5170dbe5DecodeLibraryPycEduHkAttendancePkgModals1(in *jlexer.Lexer, out *Attendance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "pycid":
			out.Pycid = string(in.String())
		case "check_in":
			if in.IsNull() {
				in.Skip()
				out.CheckIn = nil
			} else {
				if out.CheckIn == nil {
					out.CheckIn = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.CheckIn).UnmarshalJSON(data))
				}
			}
		case "check_out":
			if in.IsNull() {
				in.Skip()
				out.CheckOut = nil
			} else {
				if out.CheckOut == nil {
					out.CheckOut = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.CheckOut).UnmarshalJSON(data))
				}
			}
		case "rank":
			out.Rank = Rank(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5170dbe5EncodeLibraryPycEduHkAttendancePkgModals1(out *jwriter.Writer, in Attendance) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Pycid != "" {
		const prefix string = ",\"pycid\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Pycid))
	}
	if in.CheckIn != nil {
		const prefix string = ",\"check_in\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((*in.CheckIn).MarshalJSON())
	}
	if in.CheckOut != nil {
		const prefix string = ",\"check_out\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Raw((*in.CheckOut).MarshalJSON())
	}
	if in.Rank != 0 {
		const prefix string = ",\"rank\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Rank))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Attendance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5170dbe5EncodeLibraryPycEduHkAttendancePkgModals1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Attendance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5170dbe5EncodeLibraryPycEduHkAttendancePkgModals1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Attendance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5170dbe5DecodeLibraryPycEduHkAttendancePkgModals1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Attendance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5170dbe5DecodeLibraryPycEduHkAttendancePkgModals1(l, v)
}
